title: Acharkit
email: masteracharkit@example.com
description: >-
  AcharKit makes it easier
  to build better Android Apps
  more quickly and with less code.
github_username:  acharkit

# Build settings
markdown: kramdown
theme: jekyll-materialdocs
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
